name: baseimage-pr-notifier
on:
  pull_request:
    types: [opened]
jobs:
  baseimage-pr-notifier:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'builder-base image') }}
    steps:
      - run: curl -X POST ${{ secrets.SLACK_WEBHOOK_URL }}

